language: python
branches:
  only:
    - master
    - /\bv[0-9]/
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install pytest
script:
  - flake8 .
  - python -m pytest qatrfm/tests
